//! ECDHE shared secret computation tests
//!
//! This module tests the [`compute_ecdhe_shared_secret`] function using
//! test vectors generated by Python's cryptography library.

use tls_decryptor::types::CurveType;
use tls_decryptor::util::compute_ecdhe_shared_secret;

use super::{hex_to_bytes, load_test_vectors};

#[test]
fn test_ecdhe_p256() {
    let vectors = load_test_vectors();
    let p256 = &vectors["ecdhe_test_vectors"]["p256"];

    let server_private_key = hex_to_bytes(p256["server_private_key"].as_str().unwrap());
    let client_public_key = hex_to_bytes(p256["client_public_key"].as_str().unwrap());
    let expected_shared_secret = hex_to_bytes(p256["shared_secret"].as_str().unwrap());

    let shared_secret = compute_ecdhe_shared_secret(
        &server_private_key,
        &client_public_key,
        CurveType::Secp256r1,
    )
    .expect("ECDHE P-256 computation failed");

    assert_eq!(
        shared_secret, expected_shared_secret,
        "P-256 shared secret does not match expected value"
    );
    assert_eq!(
        shared_secret.len(),
        32,
        "P-256 shared secret should be 32 bytes"
    );
}

#[test]
fn test_ecdhe_p384() {
    let vectors = load_test_vectors();
    let p384 = &vectors["ecdhe_test_vectors"]["p384"];

    let server_private_key = hex_to_bytes(p384["server_private_key"].as_str().unwrap());
    let client_public_key = hex_to_bytes(p384["client_public_key"].as_str().unwrap());
    let expected_shared_secret = hex_to_bytes(p384["shared_secret"].as_str().unwrap());

    let shared_secret = compute_ecdhe_shared_secret(
        &server_private_key,
        &client_public_key,
        CurveType::Secp384r1,
    )
    .expect("ECDHE P-384 computation failed");

    assert_eq!(
        shared_secret, expected_shared_secret,
        "P-384 shared secret does not match expected value"
    );
    assert_eq!(
        shared_secret.len(),
        48,
        "P-384 shared secret should be 48 bytes"
    );
}

#[test]
fn test_ecdhe_p521() {
    let vectors = load_test_vectors();
    let p521 = &vectors["ecdhe_test_vectors"]["p521"];

    let server_private_key = hex_to_bytes(p521["server_private_key"].as_str().unwrap());
    let client_public_key = hex_to_bytes(p521["client_public_key"].as_str().unwrap());
    let expected_shared_secret = hex_to_bytes(p521["shared_secret"].as_str().unwrap());

    let shared_secret = compute_ecdhe_shared_secret(
        &server_private_key,
        &client_public_key,
        CurveType::Secp521r1,
    )
    .expect("ECDHE P-521 computation failed");

    assert_eq!(
        shared_secret, expected_shared_secret,
        "P-521 shared secret does not match expected value"
    );
    assert_eq!(
        shared_secret.len(),
        66,
        "P-521 shared secret should be 66 bytes"
    );
}

#[test]
fn test_ecdhe_p521_65byte_private_key() {
    // Test P-521 with 65-byte private key (when leading bit is 0)
    let vectors = load_test_vectors();
    let p521_65 = &vectors["ecdhe_test_vectors"]["p521_65byte"];

    let server_private_key = hex_to_bytes(p521_65["server_private_key"].as_str().unwrap());
    let client_public_key = hex_to_bytes(p521_65["client_public_key"].as_str().unwrap());
    let expected_shared_secret = hex_to_bytes(p521_65["shared_secret"].as_str().unwrap());

    // Verify the private key is 65 bytes
    assert_eq!(
        server_private_key.len(),
        65,
        "P-521 private key should be 65 bytes"
    );

    let shared_secret = compute_ecdhe_shared_secret(
        &server_private_key,
        &client_public_key,
        CurveType::Secp521r1,
    )
    .expect("ECDHE P-521 65-byte computation failed");

    assert_eq!(
        shared_secret, expected_shared_secret,
        "P-521 65-byte shared secret does not match expected value"
    );
    assert_eq!(
        shared_secret.len(),
        66,
        "P-521 shared secret should be 66 bytes"
    );
}

#[test]
fn test_ecdhe_x25519() {
    let vectors = load_test_vectors();
    let x25519 = &vectors["ecdhe_test_vectors"]["x25519"];

    let server_private_key = hex_to_bytes(x25519["server_private_key"].as_str().unwrap());
    let client_public_key = hex_to_bytes(x25519["client_public_key"].as_str().unwrap());
    let expected_shared_secret = hex_to_bytes(x25519["shared_secret"].as_str().unwrap());

    let shared_secret =
        compute_ecdhe_shared_secret(&server_private_key, &client_public_key, CurveType::X25519)
            .expect("ECDHE X25519 computation failed");

    assert_eq!(
        shared_secret, expected_shared_secret,
        "X25519 shared secret does not match expected value"
    );
    assert_eq!(
        shared_secret.len(),
        32,
        "X25519 shared secret should be 32 bytes"
    );
}

#[test]
fn test_ecdhe_symmetric() {
    // Test that both directions compute the same shared secret
    let vectors = load_test_vectors();
    let p256 = &vectors["ecdhe_test_vectors"]["p256"];

    let server_private_key = hex_to_bytes(p256["server_private_key"].as_str().unwrap());
    let server_public_key = hex_to_bytes(p256["server_public_key"].as_str().unwrap());
    let client_private_key = hex_to_bytes(p256["client_private_key"].as_str().unwrap());
    let client_public_key = hex_to_bytes(p256["client_public_key"].as_str().unwrap());

    // Server computes shared secret using client's public key
    let server_shared = compute_ecdhe_shared_secret(
        &server_private_key,
        &client_public_key,
        CurveType::Secp256r1,
    )
    .expect("Server ECDHE computation failed");

    // Client computes shared secret using server's public key
    let client_shared = compute_ecdhe_shared_secret(
        &client_private_key,
        &server_public_key,
        CurveType::Secp256r1,
    )
    .expect("Client ECDHE computation failed");

    assert_eq!(
        server_shared, client_shared,
        "Server and client should compute the same shared secret"
    );
}
