//! TLS 1.3 ECDHE shared secret computation tests
//!
//! This module tests the TLS 1.3 ECDHE shared secret computation using
//! test vectors generated by Python's cryptography library.

use tls_decryptor::types::CurveType;
use tls_decryptor::util::compute_shared_secret_tls13;

use super::{hex_to_bytes, load_test_vectors};

/// Parse key share entry from TLS 1.3 key_share extension data
/// Format: group (2) + key_exchange_length (2) + key_exchange
fn parse_key_share_entry(data: &[u8]) -> Option<(u16, &[u8])> {
    if data.len() < 4 {
        return None;
    }

    let group = u16::from_be_bytes([data[0], data[1]]);
    let kx_len = u16::from_be_bytes([data[2], data[3]]) as usize;

    if data.len() < 4 + kx_len {
        return None;
    }

    Some((group, &data[4..4 + kx_len]))
}

#[test]
fn test_tls13_shared_secret_p256() {
    let vectors = load_test_vectors();
    let tls13 = &vectors["tls13_test_vectors"]["ecdhe_p256"];

    let server_private_key = hex_to_bytes(tls13["server_private_key"].as_str().unwrap());
    let client_key_share_entry = hex_to_bytes(tls13["client_key_share_entry"].as_str().unwrap());
    let expected_shared_secret = hex_to_bytes(tls13["expected_shared_secret"].as_str().unwrap());

    // Parse key share entry to get client public key
    let (group, client_public_key) =
        parse_key_share_entry(&client_key_share_entry).expect("Failed to parse key share entry");

    // Verify the curve type
    let curve = CurveType::from_u16(group).expect("Invalid curve type");
    assert_eq!(curve, CurveType::Secp256r1, "Expected P-256 curve");

    let shared_secret = compute_shared_secret_tls13(&server_private_key, client_public_key, curve)
        .expect("TLS 1.3 shared secret computation failed");

    assert_eq!(
        shared_secret, expected_shared_secret,
        "TLS 1.3 shared secret does not match expected value"
    );
    assert_eq!(
        shared_secret.len(),
        32,
        "P-256 shared secret should be 32 bytes"
    );
}

#[test]
fn test_tls13_shared_secret_symmetric() {
    // Test that both directions compute the same shared secret
    let vectors = load_test_vectors();
    let tls13 = &vectors["tls13_test_vectors"]["ecdhe_p256"];

    let server_private_key = hex_to_bytes(tls13["server_private_key"].as_str().unwrap());
    let client_key_share_entry = hex_to_bytes(tls13["client_key_share_entry"].as_str().unwrap());
    let server_key_share_entry = hex_to_bytes(tls13["server_key_share_entry"].as_str().unwrap());

    // Parse key share entries
    let (_, client_public_key) = parse_key_share_entry(&client_key_share_entry)
        .expect("Failed to parse client key share entry");
    let _ = parse_key_share_entry(&server_key_share_entry)
        .expect("Failed to parse server key share entry");

    // We need client private key to test symmetry
    // For this test, we just verify that the server can compute the shared secret
    let shared_secret =
        compute_shared_secret_tls13(&server_private_key, client_public_key, CurveType::Secp256r1)
            .expect("TLS 1.3 shared secret computation failed");

    assert_eq!(
        shared_secret.len(),
        32,
        "P-256 shared secret should be 32 bytes"
    );
}
