//! TLS 1.2 ECDHE pre-master secret computation tests
//!
//! This module tests the TLS 1.2 ECDHE pre-master secret computation using
//! test vectors generated by Python's cryptography library.

use tls_decryptor::types::CurveType;
use tls_decryptor::util::{
    compute_pre_master_secret_ecdhe, compute_pre_master_secret_from_key_exchange,
    extract_server_public_key,
};

use super::{hex_to_bytes, load_test_vectors};

#[test]
fn test_tls12_ecdhe_pre_master_secret() {
    let vectors = load_test_vectors();
    let tls12 = &vectors["tls12_test_vectors"]["ecdhe_p256"];

    let server_private_key = hex_to_bytes(tls12["server_private_key"].as_str().unwrap());
    let client_public_key = hex_to_bytes(tls12["client_key_exchange"].as_str().unwrap());
    let expected_pre_master_secret =
        hex_to_bytes(tls12["expected_pre_master_secret"].as_str().unwrap());

    // ClientKeyExchange format: public_key_length (1) + public_key
    // Skip the length byte to get the actual public key
    let client_public_key_bytes = &client_public_key[1..];

    let pre_master_secret = compute_pre_master_secret_ecdhe(
        &server_private_key,
        client_public_key_bytes,
        CurveType::Secp256r1,
    )
    .expect("TLS 1.2 ECDHE pre-master secret computation failed");

    assert_eq!(
        pre_master_secret, expected_pre_master_secret,
        "TLS 1.2 ECDHE pre-master secret does not match expected value"
    );
    assert_eq!(
        pre_master_secret.len(),
        32,
        "P-256 pre-master secret should be 32 bytes"
    );
}

#[test]
fn test_tls12_extract_server_public_key() {
    let vectors = load_test_vectors();
    let tls12 = &vectors["tls12_test_vectors"]["ecdhe_p256"];

    let server_key_exchange = hex_to_bytes(tls12["server_key_exchange"].as_str().unwrap());

    let server_pk = extract_server_public_key(&server_key_exchange)
        .expect("Failed to extract server public key");

    assert!(server_pk.is_ecdhe(), "Should be ECDHE key exchange");
    assert_eq!(
        server_pk.curve(),
        Some(CurveType::Secp256r1),
        "Curve should be P-256"
    );
    assert_eq!(
        server_pk.public_key.len(),
        65,
        "P-256 uncompressed public key should be 65 bytes"
    );
}

#[test]
fn test_tls12_compute_pre_master_secret_from_key_exchange() {
    let vectors = load_test_vectors();
    let tls12 = &vectors["tls12_test_vectors"]["ecdhe_p256"];

    let server_private_key = hex_to_bytes(tls12["server_private_key"].as_str().unwrap());
    let client_key_exchange = hex_to_bytes(tls12["client_key_exchange"].as_str().unwrap());
    let server_key_exchange = hex_to_bytes(tls12["server_key_exchange"].as_str().unwrap());
    let expected_pre_master_secret =
        hex_to_bytes(tls12["expected_pre_master_secret"].as_str().unwrap());

    let pre_master_secret = compute_pre_master_secret_from_key_exchange(
        &server_private_key,
        &client_key_exchange,
        &server_key_exchange,
    )
    .expect("TLS 1.2 compute_pre_master_secret_from_key_exchange failed");

    assert_eq!(
        pre_master_secret, expected_pre_master_secret,
        "TLS 1.2 pre-master secret does not match expected value"
    );
}
