//! Integration tests for cipher module
//!
//! This module contains integration tests for the TLS decryptor cipher module,
//! using test vectors generated by Python's cryptography library.

mod tls12_cipher_tests;
mod tls13_cipher_tests;

/// Decode hex string to bytes
fn hex_decode(hex: &str) -> Result<Vec<u8>, String> {
    let mut bytes = Vec::new();
    let mut chars = hex.chars().peekable();

    while let Some(a) = chars.next() {
        let b = chars.next().ok_or("Odd number of hex digits")?;

        let high = a.to_digit(16).ok_or(format!("Invalid hex digit: {}", a))? as u8;
        let low = b.to_digit(16).ok_or(format!("Invalid hex digit: {}", b))? as u8;

        bytes.push((high << 4) | low);
    }

    Ok(bytes)
}

/// Convert hex string to bytes
pub fn hex_to_bytes(hex: &str) -> Vec<u8> {
    let hex = if hex.starts_with("0x") || hex.starts_with("0X") {
        &hex[2..]
    } else {
        hex
    };
    hex_decode(hex).expect("Invalid hex string")
}

/// Load cipher test vectors from JSON file
pub fn load_test_vectors() -> serde_json::Value {
    let json_str = include_str!("test_vectors.json");
    serde_json::from_str(json_str).expect("Failed to parse test_vectors.json")
}
