//! TLS 1.2 Cipher Tests
//!
//! This module tests the TLS 1.2 cipher decryption implementation using
//! test vectors generated by Python's cryptography library.

use tls_decryptor::cipher::suites::{
    TlsEcdheRsaWithChaCha20Poly1305Sha256, TlsRsaWithAes128GcmSha256, TlsRsaWithAes256GcmSha384,
};
use tls_decryptor::cipher::trait_def::CipherContext;

use super::hex_to_bytes;
use super::load_test_vectors;

#[test]
fn test_tls12_rsa_aes_128_gcm_decrypt() {
    let vectors = load_test_vectors();
    let test = &vectors["tls12_tests"]["rsa_aes_128_gcm_basic"];

    let cipher = TlsRsaWithAes128GcmSha256;
    let key = hex_to_bytes(test["key"].as_str().unwrap());
    let iv = hex_to_bytes(test["salt"].as_str().unwrap()); // TLS 1.2 uses salt as IV
    let ciphertext = hex_to_bytes(test["full_ciphertext"].as_str().unwrap());
    let aad = hex_to_bytes(test["aad"].as_str().unwrap());
    let expected_plaintext = hex_to_bytes(test["plaintext"].as_str().unwrap());

    let result = cipher
        .decrypt(&key, &iv, &ciphertext, &aad, 0)
        .expect("TLS 1.2 RSA AES-128-GCM decryption failed");

    assert_eq!(
        result, expected_plaintext,
        "TLS 1.2 RSA AES-128-GCM plaintext mismatch"
    );
}

#[test]
fn test_tls12_rsa_aes_256_gcm_decrypt() {
    let vectors = load_test_vectors();
    let test = &vectors["tls12_tests"]["rsa_aes_256_gcm_basic"];

    let cipher = TlsRsaWithAes256GcmSha384;
    let key = hex_to_bytes(test["key"].as_str().unwrap());
    let iv = hex_to_bytes(test["salt"].as_str().unwrap()); // TLS 1.2 uses salt as IV
    let ciphertext = hex_to_bytes(test["full_ciphertext"].as_str().unwrap());
    let aad = hex_to_bytes(test["aad"].as_str().unwrap());
    let expected_plaintext = hex_to_bytes(test["plaintext"].as_str().unwrap());

    let result = cipher
        .decrypt(&key, &iv, &ciphertext, &aad, 0)
        .expect("TLS 1.2 RSA AES-256-GCM decryption failed");

    assert_eq!(
        result, expected_plaintext,
        "TLS 1.2 RSA AES-256-GCM plaintext mismatch"
    );
}

#[test]
fn test_tls12_ecdhe_chacha20_poly1305_decrypt() {
    let vectors = load_test_vectors();
    let test = &vectors["tls12_tests"]["ecdhe_chacha20_poly1305_basic"];

    let cipher = TlsEcdheRsaWithChaCha20Poly1305Sha256;
    let key = hex_to_bytes(test["key"].as_str().unwrap());
    let iv = hex_to_bytes(test["iv"].as_str().unwrap());
    let ciphertext = hex_to_bytes(test["full_ciphertext"].as_str().unwrap());
    let aad = hex_to_bytes(test["aad"].as_str().unwrap());
    let expected_plaintext = hex_to_bytes(test["plaintext"].as_str().unwrap());

    let result = cipher
        .decrypt(&key, &iv, &ciphertext, &aad, 0)
        .expect("TLS 1.2 ECDHE ChaCha20-Poly1305 decryption failed");

    assert_eq!(
        result, expected_plaintext,
        "TLS 1.2 ECDHE ChaCha20-Poly1305 plaintext mismatch"
    );
}

#[test]
fn test_tls12_cipher_context_properties() {
    let aes128 = TlsRsaWithAes128GcmSha256;
    assert_eq!(aes128.key_length(), 16);
    assert_eq!(aes128.iv_length(), 4); // TLS 1.2 GCM uses 4-byte salt
    assert_eq!(aes128.tag_length(), 16);
    assert!(aes128.needs_explicit_nonce());

    let aes256 = TlsRsaWithAes256GcmSha384;
    assert_eq!(aes256.key_length(), 32);
    assert_eq!(aes256.iv_length(), 4); // TLS 1.2 GCM uses 4-byte salt
    assert_eq!(aes256.tag_length(), 16);
    assert!(aes256.needs_explicit_nonce());

    let chacha = TlsEcdheRsaWithChaCha20Poly1305Sha256;
    assert_eq!(chacha.key_length(), 32);
    assert_eq!(chacha.iv_length(), 12);
    assert_eq!(chacha.tag_length(), 16);
    assert!(!chacha.needs_explicit_nonce()); // ChaCha20-Poly1305 doesn't use explicit nonce
}

#[test]
fn test_tls12_rsa_aes_128_gcm_invalid_key_length() {
    let cipher = TlsRsaWithAes128GcmSha256;
    let key = vec![0u8; 8]; // Invalid key length
    let iv = vec![0u8; 4];
    // TLS 1.2: explicit_nonce (8) + tag (16) = 24 bytes minimum
    let ciphertext = vec![0u8; 24];
    let aad = vec![];

    let result = cipher.decrypt(&key, &iv, &ciphertext, &aad, 0);
    assert!(result.is_err());
}

#[test]
fn test_tls12_rsa_aes_128_gcm_invalid_iv_length() {
    let cipher = TlsRsaWithAes128GcmSha256;
    let key = vec![0u8; 16];
    let iv = vec![0u8; 8]; // Invalid IV length (should be 4)
    let ciphertext = vec![0u8; 24];
    let aad = vec![];

    let result = cipher.decrypt(&key, &iv, &ciphertext, &aad, 0);
    assert!(result.is_err());
}

#[test]
fn test_tls12_rsa_aes_128_gcm_insufficient_data() {
    let cipher = TlsRsaWithAes128GcmSha256;
    let key = vec![0u8; 16];
    let iv = vec![0u8; 4];
    let ciphertext = vec![0u8; 4]; // Too short (less than explicit_nonce)
    let aad = vec![];

    let result = cipher.decrypt(&key, &iv, &ciphertext, &aad, 0);
    assert!(result.is_err());
}

#[test]
fn test_tls12_ecdhe_chacha20_poly1305_invalid_key_length() {
    let cipher = TlsEcdheRsaWithChaCha20Poly1305Sha256;
    let key = vec![0u8; 16]; // Invalid key length
    let iv = vec![0u8; 12];
    let ciphertext = vec![0u8; 16];
    let aad = vec![];

    let result = cipher.decrypt(&key, &iv, &ciphertext, &aad, 0);
    assert!(result.is_err());
}

#[test]
fn test_tls12_ecdhe_chacha20_poly1305_invalid_iv_length() {
    let cipher = TlsEcdheRsaWithChaCha20Poly1305Sha256;
    let key = vec![0u8; 32];
    let iv = vec![0u8; 8]; // Invalid IV length
    let ciphertext = vec![0u8; 16];
    let aad = vec![];

    let result = cipher.decrypt(&key, &iv, &ciphertext, &aad, 0);
    assert!(result.is_err());
}

#[test]
fn test_tls12_ecdhe_chacha20_poly1305_insufficient_data() {
    let cipher = TlsEcdheRsaWithChaCha20Poly1305Sha256;
    let key = vec![0u8; 32];
    let iv = vec![0u8; 12];
    let ciphertext = vec![0u8; 4]; // Too short (less than tag length)
    let aad = vec![];

    let result = cipher.decrypt(&key, &iv, &ciphertext, &aad, 0);
    assert!(result.is_err());
}
