//! TLS 1.3 Cipher Tests
//!
//! This module tests the TLS 1.3 cipher decryption implementation using
//! test vectors generated by Python's cryptography library.

use tls_decryptor::cipher::suites::{
    Tls13Aes128GcmSha256, Tls13Aes256GcmSha384, Tls13ChaCha20Poly1305Sha256,
};
use tls_decryptor::cipher::trait_def::CipherContext;

use super::hex_to_bytes;
use super::load_test_vectors;

#[test]
fn test_tls13_aes_128_gcm_decrypt() {
    let vectors = load_test_vectors();
    let test = &vectors["tls13_tests"]["aes_128_gcm_basic"];

    let cipher = Tls13Aes128GcmSha256;
    let key = hex_to_bytes(test["key"].as_str().unwrap());
    let iv = hex_to_bytes(test["iv"].as_str().unwrap());
    let ciphertext = hex_to_bytes(test["full_ciphertext"].as_str().unwrap());
    let aad = hex_to_bytes(test["aad"].as_str().unwrap());
    let expected_plaintext = hex_to_bytes(test["plaintext"].as_str().unwrap());

    let result = cipher
        .decrypt(&key, &iv, &ciphertext, &aad, 0)
        .expect("TLS 1.3 AES-128-GCM decryption failed");

    assert_eq!(
        result, expected_plaintext,
        "TLS 1.3 AES-128-GCM plaintext mismatch"
    );
}

#[test]
fn test_tls13_aes_256_gcm_decrypt() {
    let vectors = load_test_vectors();
    let test = &vectors["tls13_tests"]["aes_256_gcm_basic"];

    let cipher = Tls13Aes256GcmSha384;
    let key = hex_to_bytes(test["key"].as_str().unwrap());
    let iv = hex_to_bytes(test["iv"].as_str().unwrap());
    let ciphertext = hex_to_bytes(test["full_ciphertext"].as_str().unwrap());
    let aad = hex_to_bytes(test["aad"].as_str().unwrap());
    let expected_plaintext = hex_to_bytes(test["plaintext"].as_str().unwrap());

    let result = cipher
        .decrypt(&key, &iv, &ciphertext, &aad, 0)
        .expect("TLS 1.3 AES-256-GCM decryption failed");

    assert_eq!(
        result, expected_plaintext,
        "TLS 1.3 AES-256-GCM plaintext mismatch"
    );
}

#[test]
fn test_tls13_chacha20_poly1305_decrypt() {
    let vectors = load_test_vectors();
    let test = &vectors["tls13_tests"]["chacha20_poly1305_basic"];

    let cipher = Tls13ChaCha20Poly1305Sha256;
    let key = hex_to_bytes(test["key"].as_str().unwrap());
    let iv = hex_to_bytes(test["iv"].as_str().unwrap());
    let ciphertext = hex_to_bytes(test["full_ciphertext"].as_str().unwrap());
    let aad = hex_to_bytes(test["aad"].as_str().unwrap());
    let expected_plaintext = hex_to_bytes(test["plaintext"].as_str().unwrap());

    let result = cipher
        .decrypt(&key, &iv, &ciphertext, &aad, 0)
        .expect("TLS 1.3 ChaCha20-Poly1305 decryption failed");

    assert_eq!(
        result, expected_plaintext,
        "TLS 1.3 ChaCha20-Poly1305 plaintext mismatch"
    );
}

#[test]
fn test_tls13_aes_128_gcm_with_sequence_number() {
    let vectors = load_test_vectors();
    let test = &vectors["advanced_tests"]["sequence_number_test"];

    let cipher = Tls13Aes128GcmSha256;
    let key = hex_to_bytes(test["key"].as_str().unwrap());
    let iv = hex_to_bytes(test["iv"].as_str().unwrap());
    let ciphertext = hex_to_bytes(test["full_ciphertext"].as_str().unwrap());
    let aad = hex_to_bytes(test["aad"].as_str().unwrap());
    let sequence_number = test["sequence_number"].as_u64().unwrap();
    let expected_plaintext = hex_to_bytes(test["plaintext"].as_str().unwrap());

    let result = cipher
        .decrypt(&key, &iv, &ciphertext, &aad, sequence_number)
        .expect("TLS 1.3 AES-128-GCM decryption with sequence number failed");

    assert_eq!(
        result, expected_plaintext,
        "TLS 1.3 AES-128-GCM plaintext mismatch with sequence number"
    );
}

#[test]
fn test_tls13_aes_128_gcm_empty_plaintext() {
    let vectors = load_test_vectors();
    let test = &vectors["advanced_tests"]["edge_cases"]["empty_plaintext"];

    let cipher = Tls13Aes128GcmSha256;
    let key = hex_to_bytes(test["key"].as_str().unwrap());
    let iv = hex_to_bytes(test["iv"].as_str().unwrap());
    let ciphertext = hex_to_bytes(test["full_ciphertext"].as_str().unwrap());
    let aad = hex_to_bytes(test["aad"].as_str().unwrap());
    let expected_plaintext = hex_to_bytes(test["plaintext"].as_str().unwrap());

    let result = cipher
        .decrypt(&key, &iv, &ciphertext, &aad, 0)
        .expect("TLS 1.3 AES-128-GCM empty plaintext decryption failed");

    assert_eq!(
        result, expected_plaintext,
        "TLS 1.3 AES-128-GCM empty plaintext mismatch"
    );
}

#[test]
fn test_tls13_cipher_context_properties() {
    let aes128 = Tls13Aes128GcmSha256;
    assert_eq!(aes128.key_length(), 16);
    assert_eq!(aes128.iv_length(), 12);
    assert_eq!(aes128.tag_length(), 16);
    assert!(!aes128.needs_explicit_nonce());

    let aes256 = Tls13Aes256GcmSha384;
    assert_eq!(aes256.key_length(), 32);
    assert_eq!(aes256.iv_length(), 12);
    assert_eq!(aes256.tag_length(), 16);
    assert!(!aes256.needs_explicit_nonce());

    let chacha = Tls13ChaCha20Poly1305Sha256;
    assert_eq!(chacha.key_length(), 32);
    assert_eq!(chacha.iv_length(), 12);
    assert_eq!(chacha.tag_length(), 16);
    assert!(!chacha.needs_explicit_nonce());
}

#[test]
fn test_tls13_decrypt_invalid_key_length() {
    let cipher = Tls13Aes128GcmSha256;
    let key = vec![0u8; 8]; // Invalid key length
    let iv = vec![0u8; 12];
    let ciphertext = vec![0u8; 16];
    let aad = vec![];

    let result = cipher.decrypt(&key, &iv, &ciphertext, &aad, 0);
    assert!(result.is_err());
}

#[test]
fn test_tls13_decrypt_invalid_iv_length() {
    let cipher = Tls13Aes128GcmSha256;
    let key = vec![0u8; 16];
    let iv = vec![0u8; 8]; // Invalid IV length
    let ciphertext = vec![0u8; 16];
    let aad = vec![];

    let result = cipher.decrypt(&key, &iv, &ciphertext, &aad, 0);
    assert!(result.is_err());
}

#[test]
fn test_tls13_decrypt_insufficient_data() {
    let cipher = Tls13Aes128GcmSha256;
    let key = vec![0u8; 16];
    let iv = vec![0u8; 12];
    let ciphertext = vec![0u8; 4]; // Too short (less than tag length)
    let aad = vec![];

    let result = cipher.decrypt(&key, &iv, &ciphertext, &aad, 0);
    assert!(result.is_err());
}
