//! TLS 1.2 Key Derivation Tests
//!
//! This module tests the TLS 1.2 key derivation implementation using
//! test vectors generated by Python's cryptography library.

use tls_decryptor::key_derivation::{Tls12KeyDeriver, derive_keys_tls12};
use tls_decryptor::types::{CipherSuite, Direction, TlsVersion};

use super::{hex_to_bytes, load_tls12_test_vectors};

/// Helper function to convert hex string to fixed-size array
fn hex_to_array<const N: usize>(hex: &str) -> [u8; N] {
    let bytes = hex_to_bytes(hex);
    bytes.try_into().expect("Hex string length mismatch")
}

#[test]
fn test_derive_keys_tls12_aes_128_gcm() {
    let vectors = load_tls12_test_vectors();
    let test = &vectors["key_derivation_tests"]["aes_128_gcm"];

    let client_random = hex_to_array::<32>(test["client_random"].as_str().unwrap());
    let server_random = hex_to_array::<32>(test["server_random"].as_str().unwrap());
    let pre_master_secret = hex_to_bytes(test["pre_master_secret"].as_str().unwrap());

    let session_key = derive_keys_tls12(
        &client_random,
        &server_random,
        &pre_master_secret,
        CipherSuite::TlsRsaWithAes128GcmSha256,
    )
    .expect("TLS 1.2 key derivation failed");

    // Verify derived keys
    let expected_client_key = hex_to_bytes(test["client_write_key"].as_str().unwrap());
    let expected_server_key = hex_to_bytes(test["server_write_key"].as_str().unwrap());
    let expected_client_iv = hex_to_bytes(test["client_write_iv"].as_str().unwrap());
    let expected_server_iv = hex_to_bytes(test["server_write_iv"].as_str().unwrap());

    assert_eq!(
        session_key.get_write_key(Direction::ClientToServer),
        &expected_client_key,
        "Client write key mismatch"
    );
    assert_eq!(
        session_key.get_write_key(Direction::ServerToClient),
        &expected_server_key,
        "Server write key mismatch"
    );
    assert_eq!(
        session_key.get_write_iv(Direction::ClientToServer),
        &expected_client_iv,
        "Client write IV mismatch"
    );
    assert_eq!(
        session_key.get_write_iv(Direction::ServerToClient),
        &expected_server_iv,
        "Server write IV mismatch"
    );
    assert_eq!(session_key.version, TlsVersion::Tls12);
    assert_eq!(
        session_key.cipher_suite,
        CipherSuite::TlsRsaWithAes128GcmSha256
    );
}

#[test]
fn test_derive_keys_tls12_aes_256_gcm() {
    let vectors = load_tls12_test_vectors();
    let test = &vectors["key_derivation_tests"]["aes_256_gcm"];

    let client_random = hex_to_array::<32>(test["client_random"].as_str().unwrap());
    let server_random = hex_to_array::<32>(test["server_random"].as_str().unwrap());
    let pre_master_secret = hex_to_bytes(test["pre_master_secret"].as_str().unwrap());

    let session_key = derive_keys_tls12(
        &client_random,
        &server_random,
        &pre_master_secret,
        CipherSuite::TlsRsaWithAes256GcmSha384,
    )
    .expect("TLS 1.2 key derivation failed");

    // Verify derived keys
    let expected_client_key = hex_to_bytes(test["client_write_key"].as_str().unwrap());
    let expected_server_key = hex_to_bytes(test["server_write_key"].as_str().unwrap());
    let expected_client_iv = hex_to_bytes(test["client_write_iv"].as_str().unwrap());
    let expected_server_iv = hex_to_bytes(test["server_write_iv"].as_str().unwrap());

    assert_eq!(
        session_key.get_write_key(Direction::ClientToServer),
        &expected_client_key,
        "Client write key mismatch"
    );
    assert_eq!(
        session_key.get_write_key(Direction::ServerToClient),
        &expected_server_key,
        "Server write key mismatch"
    );
    assert_eq!(
        session_key.get_write_iv(Direction::ClientToServer),
        &expected_client_iv,
        "Client write IV mismatch"
    );
    assert_eq!(
        session_key.get_write_iv(Direction::ServerToClient),
        &expected_server_iv,
        "Server write IV mismatch"
    );
    assert_eq!(session_key.version, TlsVersion::Tls12);
    assert_eq!(
        session_key.cipher_suite,
        CipherSuite::TlsRsaWithAes256GcmSha384
    );
}

#[test]
fn test_tls12_key_deriver_state_machine() {
    let vectors = load_tls12_test_vectors();
    let test = &vectors["state_machine_tests"]["basic_flow"];

    let client_random = hex_to_array::<32>(test["client_random"].as_str().unwrap());
    let server_random = hex_to_array::<32>(test["server_random"].as_str().unwrap());
    let pre_master_secret = hex_to_bytes(test["pre_master_secret"].as_str().unwrap());

    let expected_client_key = hex_to_bytes(test["expected_client_write_key"].as_str().unwrap());
    let expected_server_key = hex_to_bytes(test["expected_server_write_key"].as_str().unwrap());
    let expected_client_iv = hex_to_bytes(test["expected_client_write_iv"].as_str().unwrap());
    let expected_server_iv = hex_to_bytes(test["expected_server_write_iv"].as_str().unwrap());

    // Create deriver and verify initial state
    let deriver = Tls12KeyDeriver::new();
    assert!(!deriver.is_parameters_ready());
    assert!(!deriver.is_complete());

    // Feed ClientHello (simulated)
    // In real usage, you would parse actual TLS records
    // For this test, we directly verify the derive_keys function works
    let session_key = derive_keys_tls12(
        &client_random,
        &server_random,
        &pre_master_secret,
        CipherSuite::TlsRsaWithAes128GcmSha256,
    )
    .expect("TLS 1.2 key derivation failed");

    // Verify derived keys match expected values
    assert_eq!(
        session_key.get_write_key(Direction::ClientToServer),
        &expected_client_key,
        "Client write key mismatch"
    );
    assert_eq!(
        session_key.get_write_key(Direction::ServerToClient),
        &expected_server_key,
        "Server write key mismatch"
    );
    assert_eq!(
        session_key.get_write_iv(Direction::ClientToServer),
        &expected_client_iv,
        "Client write IV mismatch"
    );
    assert_eq!(
        session_key.get_write_iv(Direction::ServerToClient),
        &expected_server_iv,
        "Server write IV mismatch"
    );
}

#[test]
fn test_tls12_key_deriver_basic_flow() {
    use tls_parser::{TlsClientHelloContents, TlsMessageHandshake, TlsServerHelloContents};

    let vectors = load_tls12_test_vectors();
    let test = &vectors["state_machine_tests"]["basic_flow"];

    let client_random = hex_to_array::<32>(test["client_random"].as_str().unwrap());
    let server_random = hex_to_array::<32>(test["server_random"].as_str().unwrap());
    let pre_master_secret = hex_to_bytes(test["pre_master_secret"].as_str().unwrap());

    let expected_client_key = hex_to_bytes(test["expected_client_write_key"].as_str().unwrap());
    let expected_server_key = hex_to_bytes(test["expected_server_write_key"].as_str().unwrap());

    // Create deriver
    let mut deriver = Tls12KeyDeriver::new();

    // Build ClientHello
    let client_hello =
        TlsClientHelloContents::new(0x0303, &client_random, None, vec![], vec![], None);

    // Feed ClientHello
    let event = deriver
        .feed_message(&TlsMessageHandshake::ClientHello(client_hello))
        .expect("Failed to feed ClientHello");
    assert!(event.is_some());

    // Build ServerHello
    let server_hello = TlsServerHelloContents::new(
        0x0303,
        &server_random,
        None,
        0x009C, // TLS_RSA_WITH_AES_128_GCM_SHA256
        0,
        None,
    );

    // Feed ServerHello
    let event = deriver
        .feed_message(&TlsMessageHandshake::ServerHello(server_hello))
        .expect("Failed to feed ServerHello");
    assert!(event.is_some());

    // Verify parameters are ready
    assert!(deriver.is_parameters_ready());
    assert_eq!(deriver.client_random(), Some(client_random));
    assert_eq!(deriver.server_random(), Some(server_random));

    // Derive keys
    let session_key = deriver
        .derive_keys(&pre_master_secret)
        .expect("Key derivation failed");

    // Verify derived keys
    assert_eq!(
        session_key.get_write_key(Direction::ClientToServer),
        &expected_client_key
    );
    assert_eq!(
        session_key.get_write_key(Direction::ServerToClient),
        &expected_server_key
    );
    assert!(deriver.is_complete());
}
