//! TLS 1.3 Key Derivation Tests
//!
//! This module tests the TLS 1.3 key derivation implementation using
//! test vectors generated by Python's cryptography library.

use tls_decryptor::key_derivation::{Tls13KeyDeriver, derive_keys_tls13};
use tls_decryptor::types::{CipherSuite, Direction, TlsVersion};

use super::{hex_to_bytes, load_tls13_test_vectors};

#[test]
fn test_derive_keys_tls13_aes_128_gcm() {
    let vectors = load_tls13_test_vectors();
    let test = &vectors["key_derivation_tests"]["aes_128_gcm"];

    let shared_secret = hex_to_bytes(test["shared_secret"].as_str().unwrap());
    let handshake_hash = hex_to_bytes(test["handshake_hash"].as_str().unwrap());

    let session_key = derive_keys_tls13(
        &shared_secret,
        CipherSuite::Tls13Aes128GcmSha256,
        &handshake_hash,
    )
    .expect("TLS 1.3 key derivation failed");

    // Verify derived keys
    let expected_client_key = hex_to_bytes(test["client_write_key"].as_str().unwrap());
    let expected_server_key = hex_to_bytes(test["server_write_key"].as_str().unwrap());
    let expected_client_iv = hex_to_bytes(test["client_write_iv"].as_str().unwrap());
    let expected_server_iv = hex_to_bytes(test["server_write_iv"].as_str().unwrap());

    assert_eq!(
        session_key.get_write_key(Direction::ClientToServer),
        &expected_client_key,
        "Client write key mismatch"
    );
    assert_eq!(
        session_key.get_write_key(Direction::ServerToClient),
        &expected_server_key,
        "Server write key mismatch"
    );
    assert_eq!(
        session_key.get_write_iv(Direction::ClientToServer),
        &expected_client_iv,
        "Client write IV mismatch"
    );
    assert_eq!(
        session_key.get_write_iv(Direction::ServerToClient),
        &expected_server_iv,
        "Server write IV mismatch"
    );
    assert_eq!(session_key.version, TlsVersion::Tls13);
    assert_eq!(session_key.cipher_suite, CipherSuite::Tls13Aes128GcmSha256);
}

#[test]
fn test_derive_keys_tls13_aes_256_gcm() {
    let vectors = load_tls13_test_vectors();
    let test = &vectors["key_derivation_tests"]["aes_256_gcm"];

    let shared_secret = hex_to_bytes(test["shared_secret"].as_str().unwrap());
    let handshake_hash = hex_to_bytes(test["handshake_hash"].as_str().unwrap());

    let session_key = derive_keys_tls13(
        &shared_secret,
        CipherSuite::Tls13Aes256GcmSha384,
        &handshake_hash,
    )
    .expect("TLS 1.3 key derivation failed");

    // Verify derived keys
    let expected_client_key = hex_to_bytes(test["client_write_key"].as_str().unwrap());
    let expected_server_key = hex_to_bytes(test["server_write_key"].as_str().unwrap());
    let expected_client_iv = hex_to_bytes(test["client_write_iv"].as_str().unwrap());
    let expected_server_iv = hex_to_bytes(test["server_write_iv"].as_str().unwrap());

    assert_eq!(
        session_key.get_write_key(Direction::ClientToServer),
        &expected_client_key,
        "Client write key mismatch"
    );
    assert_eq!(
        session_key.get_write_key(Direction::ServerToClient),
        &expected_server_key,
        "Server write key mismatch"
    );
    assert_eq!(
        session_key.get_write_iv(Direction::ClientToServer),
        &expected_client_iv,
        "Client write IV mismatch"
    );
    assert_eq!(
        session_key.get_write_iv(Direction::ServerToClient),
        &expected_server_iv,
        "Server write IV mismatch"
    );
    assert_eq!(session_key.version, TlsVersion::Tls13);
    assert_eq!(session_key.cipher_suite, CipherSuite::Tls13Aes256GcmSha384);
}

#[test]
fn test_tls13_key_deriver_state_machine() {
    let vectors = load_tls13_test_vectors();
    let test = &vectors["state_machine_tests"]["basic_flow"];

    let shared_secret = hex_to_bytes(test["shared_secret"].as_str().unwrap());
    let handshake_hash = hex_to_bytes(test["handshake_hash"].as_str().unwrap());

    let expected_client_key = hex_to_bytes(test["expected_client_write_key"].as_str().unwrap());
    let expected_server_key = hex_to_bytes(test["expected_server_write_key"].as_str().unwrap());
    let expected_client_iv = hex_to_bytes(test["expected_client_write_iv"].as_str().unwrap());
    let expected_server_iv = hex_to_bytes(test["expected_server_write_iv"].as_str().unwrap());

    // Create deriver with shared secret
    let deriver = Tls13KeyDeriver::new(shared_secret.clone());

    // Verify initial state
    assert!(!deriver.is_complete());
    assert!(!deriver.is_handshake_keys_ready());

    // For state machine testing, we use the derive_keys_tls13 function directly
    // since the full state machine requires parsing actual TLS records
    let session_key = derive_keys_tls13(
        &shared_secret,
        CipherSuite::Tls13Aes128GcmSha256,
        &handshake_hash,
    )
    .expect("TLS 1.3 key derivation failed");

    // Verify derived keys match expected values
    assert_eq!(
        session_key.get_write_key(Direction::ClientToServer),
        &expected_client_key,
        "Client write key mismatch"
    );
    assert_eq!(
        session_key.get_write_key(Direction::ServerToClient),
        &expected_server_key,
        "Server write key mismatch"
    );
    assert_eq!(
        session_key.get_write_iv(Direction::ClientToServer),
        &expected_client_iv,
        "Client write IV mismatch"
    );
    assert_eq!(
        session_key.get_write_iv(Direction::ServerToClient),
        &expected_server_iv,
        "Server write IV mismatch"
    );
}

#[test]
fn test_derive_keys_tls13_consistency() {
    // Test that the same inputs always produce the same outputs
    let vectors = load_tls13_test_vectors();
    let test = &vectors["key_derivation_tests"]["aes_128_gcm"];

    let shared_secret = hex_to_bytes(test["shared_secret"].as_str().unwrap());
    let handshake_hash = hex_to_bytes(test["handshake_hash"].as_str().unwrap());

    let session_key1 = derive_keys_tls13(
        &shared_secret,
        CipherSuite::Tls13Aes128GcmSha256,
        &handshake_hash,
    )
    .expect("First key derivation failed");

    let session_key2 = derive_keys_tls13(
        &shared_secret,
        CipherSuite::Tls13Aes128GcmSha256,
        &handshake_hash,
    )
    .expect("Second key derivation failed");

    assert_eq!(
        session_key1.get_write_key(Direction::ClientToServer),
        session_key2.get_write_key(Direction::ClientToServer),
        "Client write key should be consistent"
    );
    assert_eq!(
        session_key1.get_write_key(Direction::ServerToClient),
        session_key2.get_write_key(Direction::ServerToClient),
        "Server write key should be consistent"
    );
}
